### ISSUE TITLE
Support bitcode builds

### ISSUE THREAD

**Issue by sharnik** [Microsoft/mobile-center-sdk-react-native#18]
When I try to build my application I get:
```
❌  ld: bitcode bundle could not be generated because '/Users/sharnik/Code/brains-and-beards/metro/remy-client/ios/Pods/RNMobileCenter/RNMobileCenter/RNMobileCenter.framework/RNMobileCenter(RNMobileCenter.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7
```

I can workaround it by disabling bitcode in my app, but probably in the long run this step shouldn't be necessary.

**Comment by dvisco** [comment]
For those that got here and are wondering how to disable bitcode - [SO](http://stackoverflow.com/questions/30848208/new-warnings-in-ios-9/30856364#30856364)

**Comment by panarasi** [comment]
cc @BretJohnson

**Comment by BretJohnson** [comment]
Thanks for the report. We'll update the SDK shortly, likely later this week, built with bitcode support enabled.

**Comment by BretJohnson** [comment]
Bitcode support is enabled now. However, we still don't recommend using bitcode for Mobile Center apps because it adds steps / complexity to getting the right dSYM files for your app to upload so Mobile Center can give user friendly crash stack traces.  But that said, bitcode should work now if you wish to build with it.
