### ISSUE TITLE
mobile-center-analytics linking error

### ISSUE THREAD

**Issue by hojberg** [Microsoft/mobile-center-sdk-react-native#24]
Trying to call `react-native link mobile-center-analytics`

Gives me a cocoapods error:

```
? For the iOS app, should user tracking be enabled automatically? Enable Automatically
Added code to initialize iOS Crashes SDK in ios/Upserve/AppDelegate.m
(node:51385) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error:
    Error: Could not find a "# Pods for" comment in your Podfile. Please add a "# Pods for Mobile Center" line
    in /Users/hojberg/code/upserve/mobile_app/ios/Podfile, inside
    the "target" section, then rerun the react-native link. Mobile Center pods will be added below the comment.

(node:51385) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

It seems really silly that things break on a missing comment lol?
Anyway.. Adding that comment I end up in this state:

```
? For the iOS app, should user tracking be enabled automatically? Enable Automatically
Added code to initialize iOS Crashes SDK in ios/Upserve/AppDelegate.m
Analyzing dependencies
Fetching podspec for `React` from `../node_modules/react-native`
[!] Unable to satisfy the following requirements:

- `MobileCenter (~> 0.4.0)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `MobileCenter (~> 0.4.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```

**Comment by BretJohnson** [comment]
@hojberg Hi. As for the comment, we use that in order to determine the spot in the Podfile where we should add the new pods (without having to do even more complicated parsing). There's normally a "#Pods for <myapp>" comment added by default when a Podfile is created by the "pod" command, but sometimes folks delete it, thus this message. Just FYI on that.

As for the error here, can you try doing a `pod repo update`, then see if it goes away. If the CocoaPods on your machine (stored in the big cocoapods github repo under ~/.cocoapods/repos) are old, that can cause this, but the `pod repo update` should fix it. Let us know if you still have any issues using the SDK. Thanks.

**Comment by hojberg** [comment]
@BretJohnson thanks! this worked for me :)
