### ISSUE TITLE
Runtime exception during initialization

### ISSUE THREAD

**Issue by skeebuzz** [Microsoft/mobile-center-sdk-react-native#34]
Setup:

- RN 0.44
- NOT using cocoapods.

App is crashing in the call to either [[RNCrashes register]] or [[RNAnalytics registerWith....]]

stacktrace:

2017-05-23 17:19:58.816 puffboard[50892:2822372] -[MSWrapperSdk initWithWrapperSdkVersion:wrapperSdkName:liveUpdateReleaseLabel:liveUpdateDeploymentKey:liveUpdatePackageHash:]: unrecognized selector sent to instance 0x600000078ec0
2017-05-23 17:19:58.829 puffboard[50892:2822372] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[MSWrapperSdk initWithWrapperSdkVersion:wrapperSdkName:liveUpdateReleaseLabel:liveUpdateDeploymentKey:liveUpdatePackageHash:]: unrecognized selector sent to instance 0x600000078ec0'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000109f6fb0b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010898e141 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000109fdf134 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x0000000109ef6840 ___forwarding___ + 1024
	4   CoreFoundation                      0x0000000109ef63b8 _CF_forwarding_prep_0 + 120
	5   puffboard                           0x0000000107d8c05b +[RNMobileCenter configureMobileCenter] + 120
	6   puffboard                           0x0000000107bcfc15 +[RNAnalytics registerWithInitiallyEnabled:] + 53
	7   puffboard                           0x0000000107bcc249 -[AppDelegate application:didFinishLaunchingWithOptions:] +

**Comment by skeebuzz** [comment]
Actually, same thing happens with cocoapods as well, even after adding the $(inherited) flag in framework search paths.

**Comment by jeveloper** [comment]
It wont work unless you move the mobilecenter.framework onto the project 
Linking doesn't do this.

**Comment by BretJohnson** [comment]
The root cause here was likely a mismatched version of the RN SDK with the native SDK.
The RN SDK update was lagging & actually paired with an older version of the native SDK. CocoaPods installs with the appropriate version dependencies, but if update to a newer version of the native SDK manually, or use a manual setup with mismatched RN SDK and native SDK, can cause an API mismatch like this.

Anyway, the current latest RN SDK, 0.5.0, is paired with the latest native SDKs, 0.9.0, so this issue should be gone. And going forward we look to ship updates to them around the same time, keeping the latest SDKs in sync.
Also, I will look at updating the doc to make all this version matching stuff clearer in the manual install instructions.
